spring:
  profiles:
    active: local
  application:
    name: oauth2
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_CLIENT_ID}
            clientSecret: ${OAUTH2_CLIENT_SECRET}

github:
  api:
    host: https://api.github.com

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG



